### ISSUE TITLE
Missing metrics for completed jobs that are automatically removed

### ISSUE THREAD

**Issue by iwpnd** [ejhayes/bull-monitor#248]
Hey @ejhayes 

do you happen to know if I have to keep completed and failed jobs saved in order for bull-monitor to work?

I have one worker with a config like so:

```typescript
    new Worker('my-queue', myJobProcessor, {
        autorun: false,
        connection: new Redis(`${process.env.REDIS_URI}`, {
            maxRetriesPerRequest: null,
        }),
        removeOnComplete: { count: 50 },
        removeOnFail: { count: 250 },
    });
```

And bull-monitor, just as expected, is able to create metrics on jobs in that queue.

Now I added another worker, and because the amount of data transmitted inside the job is too big, I'm deleting completed and failed job right away like so:

```typescript
    new Worker('my-other-queue', myOtherJobProcessor, {
        autorun: false,
        connection: new Redis(`${process.env.REDIS_URI}`, {
            maxRetriesPerRequest: null,
        }),
        removeOnComplete: { count: 0 },
        removeOnFail: { count: 0 },
    });
```

For the latter bull-monitor is crashing on me with the following:

```
TypeError: Cannot read properties of undefined (reading 'name')
at QueueEvents.<anonymous> (/src/bull/bullmq-metrics.factory.ts:267:37)
...
```

which looks like to come down on the queueEvents in the bull-metrics.factory

[example bullmq-metrics.factory.ts#L204](https://github.com/ejhayes/bull-monitor/blob/ca22edc6b74872d96853333510f0d542e018201e/src/bull/bullmq-metrics.factory.ts#L204)
```typescript
    queueEvents.on('stalled', async (event) => {
      const job = await queue.getJob(event.jobId);
      const jobLabels = {
        [LABEL_NAMES.JOB_NAME]: job.name,
        ...labels,
      };
      this.jobs_stalled.inc(jobLabels, 1);
    });
```

Am I correct to assume that `.getJob(event.jobId)` returns `undefined` at this point so the the labels cannot be build for the job when I'm not retaining some of the completed and failed jobs?

**Comment by ejhayes** [comment]
This is a good question @iwpnd. I don't think I had considered jobs that are removed right upon completion and can't say for certain whether or not any job information would be available by the time it gets to the metrics module. Based on what you've provided though I think I'll need to refactor this a bit (thanks for identifying!). A PR would be welcome if you have time.

In regards to the metrics that get generated: these are not persisted long term by this tool alone. The metrics you see here are only based on data captured while the bull monitor tool was running (restarting the process wipes the metrics). This is because Prometheus winds up scraping data every couple seconds and then persists the data to its internal data store. That way even if bull monitor gets restarted we still have all the metrics data previously captured by Prometheus, minus perhaps a couple seconds where the process was restarting. In general this metrics data presents a best effort picture of job processing that should be highly accurate but not 100% accurate.

**Comment by ejhayes** [comment]
Also @iwpnd can you try setting both age and count properties in your example? Use count 50 and age 60.

**Comment by iwpnd** [comment]
> Also @iwpnd can you try setting both age and count properties in your example? Use count 50 and age 60.

Happy to give this a try tomorrow. 👍 

> A PR would be welcome if you have time.

Would you suggest, say the removed jobs are the issue here, to refactor the queueEvents like so:

```
    queueEvents.on('stalled', async (event) => {
      const { name } = await queue.getJob(event.jobId);
      const jobLabels = {
        [LABEL_NAMES.JOB_NAME]: name || 'unknown',
        ...labels,
      };
      this.jobs_stalled.inc(jobLabels, 1);
    });
```

To at least increment an unknown label if the actual job name is no longer present? Or would you rather not increment the counter at all in that case?

**Comment by ejhayes** [comment]
@iwpnd I think the best first step is to see if the count/age update make a difference.

In terms of a PR would probably need to get rid of `queue.getJob` in favor of only looking at the details of the `event` object. Best to see what is going on before opening a PR though.

**Comment by iwpnd** [comment]
I will look into whether keeping a count/age makes a difference first of course, don't wanna waste any time either. 🙂

**Comment by iwpnd** [comment]
@ejhayes like I thought, not retaining the completed/failed events for at least the time it takes to act on the events will fail the metrics collection. By either retaining a `count` number of jobs or attach an `age` fixes the issue. 
Therefore the only PR necessary is an update of the readme with a note.

**Comment by ejhayes** [comment]
Good to know @iwpnd, thanks for checking this!
